server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  config:
    activate:
      on-profile: local-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kingpoll
    username: root
    password: 123
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
---
spring:
  config:
    activate:
      on-profile: local-session-redis
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: local-db-redis
db-redis:
  host: localhost
  port: 6380
  password:
---
spring:
  config:
    activate:
      on-profile: local-cache-redis
cache-redis:
  host: localhost
  port: 6381
  password:
